baseURL: ""
languageCode: "en-us"
title: "dreamlog"
hasCJKLanguage: true
params: 
  heading: "dreamlog"
frontmatter: 
  date: 
    - :filename
permalinks: 
  posts: /:year/:month/:day/:title/
blackfriday: 
  fractions: false
  extensionsmask: 
    - noIntraEmphasis
markup: 
  goldmark: 
    renderer: 
      unsafe: true 